###Dodaj polise:**

POST http://localhost:8080/policies
Content-Type: application/json

{
  "policyNumber": "POL-2026-001",
  "type": "OC",
  "holderName": "Anna Kowalska",
  "premiumAmount": 1200.00,
  "startDate": "2026-08-21",
  "endDate": "2027-08-21"
}
###Lista polis:**
GET http://localhost:8080/policies

###Polisy po typie:**
GET http://localhost:8080/policies/type/OC

###Walidacja — brak policyNumber:**
POST http://localhost:8080/policies
Content-Type: application/json

{
  "policyNumber": "",
  "type": "OC",
  "holderName": "Anna Kowalska",
  "premiumAmount": 1200.00,
  "startDate": "2026-08-21",
  "endDate": "2027-08-21"
}

###Lekcja 12.2
### Dodaj polise z enumem:

POST http://localhost:8080/policies
Content-Type: application/json

{
 "policyNumber": "POL-2026-002",
  "type": "AC",
  "holderName": "Jan Nowak",
  "premiumAmount": 2400.00,
  "startDate": "2026-08-21",
  "endDate": "2027-08-21"
}

###Sprobuj wyslac nieistniejacy typ:

POST http://localhost:8080/policies
Content-Type: application/json

{
"policyNumber": "POL-2026-003",
"type": "NIEZNANY_TYP",
"holderName": "Anna Nowak",
"premiumAmount": 1000.00,
"startDate": "2026-08-21",
"endDate": "2027-08-21"
}

###Lekcja 12.3
###**Dodaj agenta:**

POST http://localhost:8080/agents
Content-Type: application/json

{
  "firstName": "Anna",
  "lastName": "Kowalska",
  "email": "anna.kowalska@ubezpieczenia.pl"
}

###Dodaj polise (jesli jeszcze nie masz):**

POST http://localhost:8080/policies
Content-Type: application/json

{
"policyNumber": "POL-2026-001",
"type": "OC",
"holderName": "Jan Nowak",
"premiumAmount": 1200.00,
"startDate": "2026-08-25",
"endDate": "2027-08-25"
}

###Przypisz polise do agenta:
POST http://localhost:8080/agents/1/policies/1

###Sprawdz agenta:

GET http://localhost:8080/agents/1
